// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SistemaLicencias.Entities.Entities
{
    public partial class tbAprovados
    {
        public int apro_Id { get; set; }
        public int soli_Id { get; set; }
        public int tili_Id { get; set; }
        public int empe_Id { get; set; }
        public int sucu_Id { get; set; }
        public DateTime? apro_Fecha { get; set; }
        public int apro_UsuCreacion { get; set; }
        public DateTime apro_FechaCreacion { get; set; }
        public int? apro_UsuModificacion { get; set; }
        public DateTime? apro_FechaModificacion { get; set; }
        public bool? apro_Estado { get; set; }

        public virtual tbUsuarios apro_UsuCreacionNavigation { get; set; }
        public virtual tbUsuarios apro_UsuModificacionNavigation { get; set; }
        public virtual tbEmpleados empe { get; set; }
        public virtual tbSolicitantes soli { get; set; }
        public virtual tbSucursales sucu { get; set; }
        public virtual tbTiposLicencias tili { get; set; }
    }
}