// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SistemaLicencias.Entities.Entities
{
    public partial class tbSolicitud
    {
        public tbSolicitud()
        {
            tbAprobados = new HashSet<tbAprobados>();
            tbRechazados = new HashSet<tbRechazados>();
        }

        public int stud_Id { get; set; }
        public int soli_Id { get; set; }
        public int sucu_Id { get; set; }
        public int tili_Id { get; set; }
        public bool stud_Pago { get; set; }
        public int stud_Intentos { get; set; }
        public int stud_UsuCreacion { get; set; }
        public DateTime stud_FechaCreacion { get; set; }
        public int? stud_UsuModificacion { get; set; }
        public DateTime? stud_FechaModificacion { get; set; }
        public bool? stud_Estado { get; set; }

        public virtual tbSolicitantes soli { get; set; }
        public virtual tbUsuarios stud_UsuCreacionNavigation { get; set; }
        public virtual tbUsuarios stud_UsuModificacionNavigation { get; set; }
        public virtual tbSucursales sucu { get; set; }
        public virtual tbTiposLicencias tili { get; set; }
        public virtual ICollection<tbAprobados> tbAprobados { get; set; }
        public virtual ICollection<tbRechazados> tbRechazados { get; set; }
    }
}