// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SistemaLicencias.Entities.Entities
{
    public partial class tbSolicitantes
    {
        public int soli_Id { get; set; }
        public string soli_Nombre { get; set; }
        public string soli_Apellido { get; set; }
        public string soli_Identidad { get; set; }
        public string soli_Sexo { get; set; }
        public DateTime soli_FechaNacimiento { get; set; }
        public string soli_Telefono { get; set; }
        public int muni_Id { get; set; }
        public string soli_Direccion { get; set; }
        public int soli_UsuCreacion { get; set; }
        public DateTime? soli_FechaCreacion { get; set; }
        public int? soli_UsuModificacion { get; set; }
        public DateTime? soli_FechaModificacion { get; set; }
        public bool? soli_Estado { get; set; }

        public virtual tbMunicipios muni { get; set; }
        public virtual tbUsuarios soli_UsuCreacionNavigation { get; set; }
        public virtual tbUsuarios soli_UsuModificacionNavigation { get; set; }
    }
}